export const productos = [
  {
    id: 1,
    nombre: "Buche",
    categoria: "carnitas",
    tipoVenta: ["taco", "medio", "kilo", "gramos"],
    precio_taco: 22,
    precio_medio: 140,
    precio_kilo: 280,
    precio_gramo: 0.28,
  },
  {
    id: 2,
    nombre: "Nana",
    categoria: "carnitas",
    tipoVenta: ["taco", "medio", "kilo", "gramos"],
    precio_taco: 24,
    precio_medio: 150,
    precio_kilo: 300,
    precio_gramo: 0.30,
  },
  {
    id: 3,
    nombre: "Maciza",
    categoria: "carnitas",
    tipoVenta: ["taco", "medio", "kilo", "gramos"],
    precio_taco: 20,
    precio_medio: 130,
    precio_kilo: 260,
    precio_gramo: 0.26,
  },
  {
    id: 4,
    nombre: "Costilla",
    categoria: "carnitas",
    tipoVenta: ["taco", "medio", "kilo", "gramos"],
    precio_taco: 25,
    precio_medio: 160,
    precio_kilo: 320,
    precio_gramo: 0.32,
  },
  {
    id: 5,
    nombre: "Patitas de puerco",
    categoria: "carnitas",
    tipoVenta: ["taco", "medio", "kilo", "gramos"],
    precio_taco: 18,
    precio_medio: 120,
    precio_kilo: 240,
    precio_gramo: 0.24,
  },
  {
    id: 6,
    nombre: "Barriga",
    categoria: "carnitas",
    tipoVenta: ["taco", "medio", "kilo", "gramos"],
    precio_taco: 23,
    precio_medio: 145,
    precio_kilo: 290,
    precio_gramo: 0.29,
  },
  {
    id: 7,
    nombre: "Trompa",
    categoria: "carnitas",
    tipoVenta: ["taco", "medio", "kilo", "gramos"],
    precio_taco: 21,
    precio_medio: 135,
    precio_kilo: 270,
    precio_gramo: 0.27,
  },
  {
    id: 8,
    nombre: "Oreja",
    categoria: "carnitas",
    tipoVenta: ["taco", "medio", "kilo", "gramos"],
    precio_taco: 19,
    precio_medio: 125,
    precio_kilo: 250,
    precio_gramo: 0.25,
  },
  {
    id: 9,
    nombre: "Cuero",
    categoria: "carnitas",
    tipoVenta: ["taco", "medio", "kilo", "gramos"],
    precio_taco: 17,
    precio_medio: 110,
    precio_kilo: 220,
    precio_gramo: 0.22,
  },
  {
    id: 10,
    nombre: "Coca-Cola 600ml",
    categoria: "refresco",
    tipoVenta: ["pieza"],
    precio_pieza: 25,
  },
  {
    id: 11,
    nombre: "Sidral 600ml",
    categoria: "refresco",
    tipoVenta: ["pieza"],
    precio_pieza: 23,
  },
  {
    id: 12,
    nombre: "Agua mineral",
    categoria: "bebida",
    tipoVenta: ["pieza"],
    precio_pieza: 20,
  },
  {
    id: 13,
    nombre: "Cerveza",
    categoria: "alcohol",
    tipoVenta: ["pieza"],
    precio_pieza: 35,
  },
  {
    id: 14,
    nombre: "Michelada",
    categoria: "alcohol",
    tipoVenta: ["pieza"],
    precio_pieza: 65,
  },
];